/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => CopyAsRichUrlPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var escapeHtml = (s) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
var CopyAsRichUrlPlugin = class extends import_obsidian.Plugin {
  async onload() {
    const doCopy = async () => {
      const file = this.app.workspace.getActiveFile();
      if (!file) {
        new import_obsidian.Notice("No active note");
        return;
      }
      const vault = this.app.vault.getName();
      const pathNoExt = file.path.replace(/\.md$/, "");
      const url = `obsidian://open?vault=${encodeURIComponent(vault)}&file=${encodeURIComponent(pathNoExt)}`;
      const title = file.basename;
      const html = `<a href="${escapeHtml(url)}">${escapeHtml(title)}</a>`;
      const plain = `${title}
${url}`;
      try {
        const item = new ClipboardItem({
          "text/html": new Blob([html], { type: "text/html" }),
          "text/plain": new Blob([plain], { type: "text/plain" })
        });
        await navigator.clipboard.write([item]);
      } catch (e) {
        await navigator.clipboard.writeText(plain);
      }
      new import_obsidian.Notice("Rich URL copied");
    };
    this.addCommand({
      id: "copy-as-rich-url",
      name: "Copy current note as rich URL",
      callback: doCopy
    });
    this.addRibbonIcon("link", "Copy as Rich URL", doCopy);
  }
};
